function opts=autonex_options(opts)
if nargin==0, opts=struct; end
defaults=struct('seed',60,'dt',.05,'duration',6,'scenario','cut_in', ...
    'trackerModel','IMM','useLearnedIntent',true, ...
    'perceptionMode','legacy','sensorAvailability',[true true true], ...
    'sensorConfig',struct, ...
    'wheelbase',2.7,'maxSteeringAngle',deg2rad(30),'maxSteeringRate',deg2rad(45), ...
    'enforcePhysicalSteeringRate',true, ...
    'maxAcceleration',1.2,'maxDeceleration',6, ...
    'controlledDeceleration',3.5,'microDeceleration',1.5, ...
    'rearRiskHorizon',6,'rearActionHorizon',3,'rearCreepSpeedKmh',5, ...
    'pathLookaheadMin',3,'pathLookaheadTime',1.0,'maxLateralAcceleration',2.5, ...
    'laneIndependent',true,'visualize',false,'exportVideo',false,'showLaneMarkings',true, ...
    'videoFile','autonex_safe_space_animation.mp4','reportFile','');
names=fieldnames(defaults);
for k=1:numel(names)
    if ~isfield(opts,names{k}), opts.(names{k})=defaults.(names{k}); end
end
end
