function build_autonex_simulink()
% Build an executable normal-mode simulation using the shared closed-loop step.
root=fileparts(mfilename('fullpath')); addpath(root);
model='main_integration'; file=fullfile(root,'simulink',[model '.slx']);
if bdIsLoaded(model), close_system(model,0); end
new_system(model);
set_param(model,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','.05','StopTime','6','InitFcn','clear autonex_simulink_step', ...
    'ReturnWorkspaceOutputs','on');
add_block('simulink/Sources/Digital Clock',[model '/Simulation Time'], ...
    'SampleTime','.05','Position',[40 80 85 110]);
add_block('simulink/User-Defined Functions/Interpreted MATLAB Fcn', ...
    [model '/Sensor Fusion Planning Guardian and Vehicle'], ...
    'Position',[155 55 435 135],'MATLABFcn','autonex_simulink_step(u)', ...
    'OutputDimensions','8');
add_block('simulink/Sinks/To Workspace',[model '/Validation Log'], ...
    'VariableName','autonex_log','SaveFormat','Array','Position',[510 65 620 105]);
add_line(model,'Simulation Time/1','Sensor Fusion Planning Guardian and Vehicle/1');
add_line(model,'Sensor Fusion Planning Guardian and Vehicle/1','Validation Log/1');
annotation=Simulink.Annotation(model, ...
    'Shared MATLAB closed loop: x, y, speed (km/h), ax, ay, tracks, emergency, collision. Normal simulation only.');
annotation.Position=[40 170];
save_system(model,file); close_system(model,0);
fprintf('Built %s\n',file);
end
