function tracker = create_autonex_gnn_tracker(model)

    if nargin<1, model='CV'; end
    initializer=@initcvkf;
    if strcmpi(model,'IMM'), initializer=@initekfimm; end
    if strcmpi(model,'CV_EKF'), initializer=@initcvekf; end

    %% =====================================================
    % AUTONEX MULTI-OBJECT GNN TRACKER
    %% =====================================================

    tracker = trackerGNN( ...
        'FilterInitializationFcn', ...
        initializer, ...
        ...
        'AssignmentThreshold', ...
        30, ...
        ...
        'ConfirmationThreshold', ...
        [2 3], ...
        ...
        'DeletionThreshold', ...
        [5 5], ...
        ...
        'MaxNumTracks', ...
        50);

end
