function tracker = create_autonex_gnn_tracker()

    %% =====================================================
    % AUTONEX MULTI-OBJECT GNN TRACKER
    %% =====================================================

    tracker = trackerGNN( ...
        'FilterInitializationFcn', ...
        @initcvkf, ...
        ...
        'AssignmentThreshold', ...
        30, ...
        ...
        'ConfirmationThreshold', ...
        [2 3], ...
        ...
        'DeletionThreshold', ...
        [5 5], ...
        ...
        'MaxNumTracks', ...
        50);

end