function speedsKmh = generate_candidate_speeds()

    % AutoNex candidate longitudinal actions
    %
    % Normal micro-adjustments first,
    % then stronger deceleration options.

    speedsKmh = [
        75 ...
        74 ...
        73 ...
        72 ...
        70 ...
        65 ...
        60 ...
        50
    ];

end