clear;
clc;
close all;

rng(60);

%% =========================================================
% AUTONEX FULL CLOSED-LOOP 2-D PLANNER
%% =========================================================

actors = ...
    create_highway_scenario();

tracker = ...
    create_autonex_gnn_tracker();


%% =========================================================
% ENVIRONMENT
%% =========================================================

environment.lightLevel = 1.0;
environment.visibility = 1.0;
environment.radarQuality = 0.95;
environment.thermalQuality = 0.85;


%% =========================================================
% SETTINGS
%% =========================================================

dt = 0.05;
T = 6.0;

planningHorizons = ...
    0.25:0.25:3.0;

egoLaneY = 7.0;

roadMinY = -1.75;
roadMaxY = 8.75;


%% =========================================================
% FIGURE
%% =========================================================

figure( ...
    'Name', ...
    'AutoNex Closed-Loop 2-D Planner');


%% =========================================================
% MANEUVER HYSTERESIS STATE
%% =========================================================

selectionState = [];


%% =========================================================
% MAIN LOOP
%% =========================================================

for t = 0:dt:T

    %% =====================================================
    % CURRENT EGO
    %% =====================================================

    ego = ...
        actors(1);

    currentSpeedKmh = ...
        ego.vx * 3.6;


    %% =====================================================
    % 1. RADAR
    %% =====================================================

    radar = ...
        scan_autonex_radar_suite( ...
            actors);

    radarObjects = ...
        radar_to_object_detections( ...
            radar, ...
            ego, ...
            t);


    %% =====================================================
    % 2. GNN TRACKING
    %% =====================================================

    [confirmedTracks,~,~] = ...
        tracker( ...
            radarObjects, ...
            t);


    %% =====================================================
    % 3. RGB CAMERA
    %% =====================================================

    rgb = ...
        simulate_rgb_camera( ...
            ego, ...
            actors, ...
            environment);


    %% =====================================================
    % 4. THERMAL IR
    %% =====================================================

    thermal = ...
        simulate_thermal_ir( ...
            ego, ...
            actors);


    %% =====================================================
    % 5. MULTIMODAL FUSION
    %% =====================================================

    fusedTracks = ...
        build_fused_track_perception( ...
            confirmedTracks, ...
            rgb, ...
            thermal, ...
            environment);


    %% =====================================================
    % 6. CUT-IN INTENT
    %% =====================================================

    intent = [];

    if ~isempty(confirmedTracks)

        [tempIntent,found] = ...
            find_highest_cutin_risk( ...
                confirmedTracks, ...
                ego, ...
                egoLaneY);

        if found

            intent = ...
                tempIntent;

        end

    end


    %% =====================================================
    % 7. GENERATE 2-D TRAJECTORIES
    %% =====================================================

    candidates = ...
        generate_2d_candidate_set( ...
            ego, ...
            planningHorizons, ...
            egoLaneY);


    %% =====================================================
    % 8. EVALUATE + SELECT + STABILIZE + GUARD
    %% =====================================================

    if ~isempty(confirmedTracks)

        %% -------------------------------------------------
        % EVALUATE TRAJECTORIES
        %% -------------------------------------------------

        results = ...
            evaluate_2d_trajectories( ...
                candidates, ...
                confirmedTracks, ...
                fusedTracks, ...
                ego, ...
                intent, ...
                roadMinY, ...
                roadMaxY);


        %% -------------------------------------------------
        % RAW PLANNER PROPOSAL
        %% -------------------------------------------------

        [proposedCandidate, ...
         proposedIndex, ...
         proposedMode] = ...
            select_best_2d_trajectory( ...
                candidates, ...
                results);


        %% -------------------------------------------------
        % MANEUVER HYSTERESIS
        %% -------------------------------------------------

        [selectedCandidate, ...
         bestIndex, ...
         selectionMode, ...
         selectionState, ...
         stabilityMode] = ...
            stabilize_trajectory_selection( ...
                candidates, ...
                results, ...
                proposedCandidate, ...
                proposedIndex, ...
                proposedMode, ...
                selectionState, ...
                t);


        %% -------------------------------------------------
        % CAT REFLEX 2-D SAFETY GUARDIAN
        %% -------------------------------------------------

        [guardianCandidate, ...
         guardianIndex, ...
         guardianMode, ...
         guardianResults] = ...
            cat_reflex_2d_guardian( ...
                candidates, ...
                results, ...
                selectedCandidate, ...
                bestIndex, ...
                confirmedTracks, ...
                roadMinY, ...
                roadMaxY);


        %% -------------------------------------------------
        % GUARDIAN HAS FINAL AUTHORITY
        %% -------------------------------------------------

        selectedCandidate = ...
            guardianCandidate;

        bestIndex = ...
            guardianIndex;


        %% -------------------------------------------------
        % SYNCHRONIZE HYSTERESIS AFTER OVERRIDE
        %% -------------------------------------------------

        if ~isempty(selectedCandidate) && ...
           ~strcmp(guardianMode,'APPROVED')

            selectionState.initialized = true;

            selectionState.name = ...
                selectedCandidate.name;

            selectionState.targetSpeedKmh = ...
                selectedCandidate.targetSpeedKmh;

            selectionState.lastSwitchTime = ...
                t;

        end


    else

        %% =================================================
        % NO CONFIRMED TRACKS YET
        %% =================================================

        selectedCandidate = ...
            candidates(1);

        bestIndex = 1;

        selectionMode = ...
            'CRUISE';

        stabilityMode = ...
            'NO_TRACKS';

        guardianMode = ...
            'NO_TRACKS';

        guardianResults = ...
            struct([]);

    end


    %% =====================================================
    % 9. TARGETS
    %% =====================================================

    if isempty(selectedCandidate)

        targetSpeedKmh = 0;

        targetY = ...
            ego.y;

        selectionMode = ...
            'EMERGENCY';

        selectedName = ...
            'NONE';

    else

        targetSpeedKmh = ...
            selectedCandidate.targetSpeedKmh;

        targetY = ...
            selectedCandidate.targetY;

        selectedName = ...
            selectedCandidate.name;

    end


    %% =====================================================
    % 10. LONGITUDINAL CAT REFLEX
    %% =====================================================

    command = ...
        cat_reflex_guardian( ...
            currentSpeedKmh, ...
            targetSpeedKmh);

    longitudinalAcceleration = ...
        speed_tracking_controller( ...
            currentSpeedKmh, ...
            targetSpeedKmh, ...
            command);


    %% =====================================================
    % 11. LATERAL CONTROLLER
    %% =====================================================

    lateralAcceleration = ...
        lateral_tracking_controller( ...
            ego.y, ...
            ego.vy, ...
            targetY);


    %% =====================================================
    % 12. APPLY CONTROL
    %% =====================================================

    actors(1).ax = ...
        longitudinalAcceleration;

    actors(1).ay = ...
        lateralAcceleration;


    %% =====================================================
    % 13. VISUALIZATION
    %% =====================================================

    clf;

    hold on;
    grid on;


    %% Road edges

    plot( ...
        [ego.x-25 ego.x+100], ...
        [roadMinY roadMinY], ...
        'k', ...
        'LineWidth',2);

    plot( ...
        [ego.x-25 ego.x+100], ...
        [roadMaxY roadMaxY], ...
        'k', ...
        'LineWidth',2);


    %% Lane separators

    plot( ...
        [ego.x-25 ego.x+100], ...
        [1.75 1.75], ...
        'k--');

    plot( ...
        [ego.x-25 ego.x+100], ...
        [5.25 5.25], ...
        'k--');


    %% -----------------------------------------------------
    % ALL CANDIDATES
    %% -----------------------------------------------------

    for i = 1:length(candidates)

        plot( ...
            candidates(i).trajectory.x, ...
            candidates(i).trajectory.y, ...
            'LineWidth',0.5);

    end


    %% -----------------------------------------------------
    % SELECTED TRAJECTORY
    %% -----------------------------------------------------

    if ~isempty(selectedCandidate)

        plot( ...
            selectedCandidate.trajectory.x, ...
            selectedCandidate.trajectory.y, ...
            'LineWidth',4);

    end


    %% -----------------------------------------------------
    % TRUE WORLD VEHICLES
    %% -----------------------------------------------------

    for i = 1:length(actors)

        plot( ...
            actors(i).x, ...
            actors(i).y, ...
            's', ...
            'MarkerSize',10, ...
            'LineWidth',2);

        text( ...
            actors(i).x + 0.7, ...
            actors(i).y + 0.20, ...
            actors(i).name);

    end


    %% -----------------------------------------------------
    % TRACKS
    %% -----------------------------------------------------

    for k = 1:length(confirmedTracks)

        state = ...
            confirmedTracks(k).State;

        plot( ...
            state(1), ...
            state(3), ...
            'x', ...
            'MarkerSize',10, ...
            'LineWidth',2);

    end


    %% -----------------------------------------------------
    % DASHBOARD
    %% -----------------------------------------------------

    dashX = ...
        ego.x - 20;


    if isempty(intent)

        pCut = 0;

    else

        pCut = ...
            intent.probability * 100;

    end


    text( ...
        dashX, ...
        8.35, ...
        sprintf( ...
            'Time %.2f s', ...
            t));


    text( ...
        dashX + 18, ...
        8.35, ...
        sprintf( ...
            'Speed %.1f km/h', ...
            currentSpeedKmh));


    text( ...
        dashX + 43, ...
        8.35, ...
        sprintf( ...
            'Target %.1f km/h', ...
            targetSpeedKmh));


    text( ...
        dashX + 68, ...
        8.35, ...
        sprintf( ...
            'Target Y %.2f', ...
            targetY));


    text( ...
        ego.x - 10, ...
        -0.5, ...
        sprintf( ...
            'P(CUT-IN) %.1f%%', ...
            pCut), ...
        'FontWeight','bold');


    text( ...
        ego.x + 20, ...
        -0.5, ...
        sprintf( ...
            '%s | %s | %s | Guardian:%s', ...
            selectionMode, ...
            selectedName, ...
            stabilityMode, ...
            guardianMode), ...
        'FontWeight','bold');


    title( ...
        'AutoNex — Closed-Loop Multimodal 2-D Cat Reflex Planner');

    xlabel( ...
        'Longitudinal X (m)');

    ylabel( ...
        'Lateral Y (m)');

    xlim( ...
        [ego.x-25 ego.x+95]);

    ylim( ...
        [-2 9]);

    drawnow;


    %% =====================================================
    % PLANNER DEBUG OUTPUT EVERY 0.25 s
    %% =====================================================

    if mod(round(t/dt),5) == 0

        if isempty(intent)

            debugPCut = 0;

        else

            debugPCut = ...
                intent.probability * 100;

        end


        fprintf( ...
            ['t=%4.2f | ' ...
             'Pcut=%5.1f%% | ' ...
             'Maneuver=%-18s | ' ...
             'Speed=%5.1f | ' ...
             'TargetY=%5.2f | ' ...
             'Planner=%s | ' ...
             'Stability=%s | ' ...
             'Guardian=%s\n'], ...
            t, ...
            debugPCut, ...
            selectedName, ...
            targetSpeedKmh, ...
            targetY, ...
            selectionMode, ...
            stabilityMode, ...
            guardianMode);

    end


    %% =====================================================
    % 14. UPDATE PHYSICAL WORLD
    %% =====================================================

    actors = ...
        update_highway_actors( ...
            actors, ...
            dt);


    %% Prevent reverse

    actors(1).vx = ...
        max( ...
            actors(1).vx, ...
            0);


    %% Keep ego physically inside road

    actors(1).y = ...
        min( ...
            max( ...
                actors(1).y, ...
                roadMinY + 0.9), ...
            roadMaxY - 0.9);


    pause(0.01);

end