function detections = scan_autonex_radar_suite(actors)

    %% Ego vehicle
    ego = actors(1);


    %% =====================================================
    % SENSOR 1 — FRONT RADAR
    %% =====================================================

    front = simulate_mmwave_radar( ...
        ego, ...
        actors, ...
        'FRONT_RADAR', ...
        0, ...          % facing forward
        120, ...        % field of view
        150);           % maximum range


    %% =====================================================
    % SENSOR 2 — REAR RADAR
    %% =====================================================

    rear = simulate_mmwave_radar( ...
        ego, ...
        actors, ...
        'REAR_RADAR', ...
        180, ...
        120, ...
        100);


    %% =====================================================
    % SENSOR 3 — LEFT CORNER RADAR
    %% =====================================================

    leftCorner = simulate_mmwave_radar( ...
        ego, ...
        actors, ...
        'LEFT_CORNER_RADAR', ...
        60, ...
        100, ...
        80);


    %% =====================================================
    % SENSOR 4 — RIGHT CORNER RADAR
    %% =====================================================

    rightCorner = simulate_mmwave_radar( ...
        ego, ...
        actors, ...
        'RIGHT_CORNER_RADAR', ...
        -60, ...
        100, ...
        80);


    %% =====================================================
    % COMBINE DETECTIONS
    %% =====================================================

    detections = [
        front ...
        rear ...
        leftCorner ...
        rightCorner
    ];

end