function row=steering_actuator_metrics(r)
s=r.samples; opts=r.options; dt=opts.dt; duration=s(end).time-s(1).time;
previous=[0 s(1:end-1).steeringAngle]; applied=[s.steeringAngle];
if isfield(s,'requestedSteeringRate')
    requested=[s.requestedSteeringRate];
else
    % Reconstruct the unchanged pre-actuator request from saved baseline data.
    override=[s.emergency] | ~strcmp({s.guardianMode},'APPROVED');
    limit=min(opts.maxSteeringAngle,atan(opts.maxLateralAcceleration*opts.wheelbase./max(([s.speed]/3.6).^2,.1)));
    limit(override)=opts.maxSteeringAngle;
    desired=max(-limit,min(limit,[s.rawSteeringAngle]));
    requested=(desired-previous)/dt;
end
rate=(applied-previous)/dt; interval=[diff([s.time]) 0];
atLimit=abs(abs(rate)-opts.maxSteeringRate)<=1e-8;
active=[s.emergency] | ~strcmp({s.guardianMode},'APPROVED') | ...
    ismember({s.longitudinalCommand},{'CONTROLLED_BRAKE','MICRO_DECELERATE','EMERGENCY_BRAKE'});
finite=all(isfinite([s.x s.y s.speed s.egoYaw applied requested rate]));
authority=all([s([s.emergency]).targetSpeed]==0) && all([s([s.emergency]).ax]<=0);
row=struct('scenarioName',opts.scenario,'duration',duration, ...
    'collisionCount',sum([s.collision]),'boundaryViolations',sum([s.boundaryViolation]), ...
    'minimumClearance',min([s.minClearance]), ...
    'maxRequestedSteeringRate',rad2deg(max(abs(requested))), ...
    'maxAppliedSteeringRate',rad2deg(max(abs(rate))), ...
    'timeAtSteeringRateLimit',sum(interval(atLimit)), ...
    'maxSteering',rad2deg(max(abs(applied))),'emergencySteps',sum([s.emergency]), ...
    'CatReflexActivations',sum(diff([false active])==1), ...
    'distance',s(end).x-s(1).x,'averageSpeed',(s(end).x-s(1).x)/duration, ...
    'NaNInfDetected',~finite,'emergencyAuthority',authority, ...
    'maximumLateralAcceleration',max(abs([s.ay])), ...
    'physicalRatePassed',max(abs(rate))<=opts.maxSteeringRate+1e-8, ...
    'PASS',false);
row.PASS=finite && authority && row.collisionCount==0 && row.boundaryViolations==0 && ...
    row.minimumClearance>=.5 && row.physicalRatePassed && ...
    row.maxSteering<=rad2deg(opts.maxSteeringAngle)+1e-8;
end
