clear;
clc;

%% =========================================================
% AUTONEX ACCELERATION-LIMITED CANDIDATE TEST
%% =========================================================

currentX = 0;

currentSpeed = ...
    75 / 3.6;


candidateSpeeds = ...
    [75 74 73 70 60 50];


horizons = ...
    [0.5 1.0 2.0];


fprintf('\n');
fprintf('============================================================\n');
fprintf(' AutoNex Acceleration-Limited Candidate Motion\n');
fprintf('============================================================\n\n');


for s = 1:length(candidateSpeeds)

    target = ...
        candidateSpeeds(s);


    fprintf( ...
        '\nTARGET = %.1f km/h\n', ...
        target);


    for h = horizons

        [futureX, futureSpeed, acceleration] = ...
            predict_ego_candidate_state( ...
                currentX, ...
                currentSpeed, ...
                target, ...
                h);


        fprintf( ...
            ['Horizon %.1f s | ' ...
             'X=%6.2f m | ' ...
             'Speed=%6.2f km/h | ' ...
             'Accel=%6.2f m/s^2\n'], ...
            h, ...
            futureX, ...
            futureSpeed * 3.6, ...
            acceleration);

    end

end