function report=validate_corridor_stability()
% Missing-lane corridor stability validation with jitter metrics.
opts=autonex_options(struct('scenario','missing_lane','showLaneMarkings',false, ...
    'reportFile','results/corridor_stability_validation.json'));
report=run_autonex_simulation(opts);
s=report.samples;
raw=[s.rawCorridorReferenceY]; stab=[s.stabilizedCorridorReferenceY];
valid=isfinite(raw)&isfinite(stab);
raw=raw(valid); stab=stab(valid);
dRaw=diff(raw); dStab=diff(stab);
report.jitter=struct( ...
    'rawTotalVariation',sum(abs(dRaw)), ...
    'stabilizedTotalVariation',sum(abs(dStab)), ...
    'rawMaxStepChange',max(abs(dRaw)), ...
    'stabilizedMaxStepChange',max(abs(dStab)), ...
    'rawDirectionReversals',sum(sign(dRaw(1:end-1))~=sign(dRaw(2:end)) & dRaw(1:end-1)~=0 & dRaw(2:end)~=0), ...
    'stabilizedDirectionReversals',sum(sign(dStab(1:end-1))~=sign(dStab(2:end)) & dStab(1:end-1)~=0 & dStab(2:end)~=0), ...
    'uniqueRawReferences',numel(unique(round(raw,2))), ...
    'uniqueStabilizedReferences',numel(unique(round(stab,2))));
modes={s.corridorStabilityMode};
report.modeCounts=struct();
for m=unique(modes), report.modeCounts.(genvarname(m{1}))=sum(strcmp(modes,m{1})); end
fprintf(['STABILITY | collision=%d | boundary=%d | clearance=%.4f m | finalSpeed=%.4f km/h | ' ...
    'distance=%.4f m | emergencySteps=%d\n'],report.collision,report.boundaryViolation, ...
    report.minClearance,report.finalSpeed,report.distance,report.emergencySteps);
fprintf(['TV(raw)=%.4f | TV(stab)=%.4f | maxStep(raw)=%.4f | maxStep(stab)=%.4f | ' ...
    'reversals(raw)=%d | reversals(stab)=%d | unique(raw)=%d | unique(stab)=%d\n'], ...
    report.jitter.rawTotalVariation,report.jitter.stabilizedTotalVariation, ...
    report.jitter.rawMaxStepChange,report.jitter.stabilizedMaxStepChange, ...
    report.jitter.rawDirectionReversals,report.jitter.stabilizedDirectionReversals, ...
    report.jitter.uniqueRawReferences,report.jitter.uniqueStabilizedReferences);
end
