function scene = urban_intersection()
%URBAN_INTERSECTION Shared prototype scene (must match python/prototype/aeb_sim.py).
    scene.name = 'urban_intersection';
    scene.dt = 0.05;
    scene.t_end = 4.0;
    scene.ttc_brake_s = 2.0;
    scene.a_brake = 6.0;
    scene.hit_dist_m = 2.4;
    scene.ego = struct('x', 0.0, 'y', 0.0, 'vx', 10.0, 'vy', 0.0, 'length', 4.5, 'width', 1.8);
    scene.objects = struct( ...
        'id', {1, 2, 3}, ...
        'label', {'car', 'pedestrian', 'cow'}, ...
        'x', {20.0, 16.0, 30.0}, ...
        'y', {3.6, -2.4, 0.15}, ...
        'vx', {8.0, 0.0, 0.4}, ...
        'vy', {0.0, 1.5, 0.0});
end
