function packet=autonex_rr_telemetry(out)
% Read-only transport schema, not a RoadRunner pose setter or dynamics model.
packet=struct('schemaVersion',1,'timeSeconds',out.time,'coordinateFrame','AUTONEX_WORLD', ...
    'egoXMetres',out.x,'egoYMetres',out.y,'egoYawRadians',out.egoYaw, ...
    'egoSpeedMetresPerSecond',out.speed/3.6,'steeringRadians',out.steeringAngle, ...
    'selectedManeuver',out.selectedName,'currentCommand',out.longitudinalCommand);
assert(all(isfinite([packet.timeSeconds packet.egoXMetres packet.egoYMetres ...
    packet.egoYawRadians packet.egoSpeedMetresPerSecond packet.steeringRadians])));
end
