function frame=autonex_telemetry_frame(out)
% Observational projection only. Never invoke sensing, prediction or planning.
frame=struct('time',out.time,'ego',struct('x',out.x,'y',out.y, ...
    'headingRad',out.egoYaw,'speedMps',out.speed/3.6,'speedKmh',out.speed, ...
    'ax',out.ax,'ay',out.ay,'steeringRad',out.steeringAngle), ...
    'decision',out.motionMode,'guardian',out.guardianMode, ...
    'collision',out.collision,'boundaryViolation',out.boundaryViolation, ...
    'minimumFootprintClearance',out.minClearance,'tracks',struct([]), ...
    'candidates',struct([]),'selected',out.selected, ...
    'predictedObjectTrajectories',[],'safetyBubble',[], ...
    'predictionAvailability','UNAVAILABLE_NOT_CAPTURED_BY_CORE', ...
    'safetyBubbleAvailability','UNAVAILABLE_NOT_CAPTURED_BY_CORE');
plain=out; plain.tracks=struct([]);
for k=1:numel(out.tracks)
    tr=out.tracks(k);
    % Snapshot public track data, not live tracker/filter handles.
    q=struct('TrackID',tr.TrackID,'State',tr.State, ...
        'StateCovariance',tr.StateCovariance,'ObjectAttributes',{tr.ObjectAttributes});
    if isempty(plain.tracks), plain.tracks=q; else, plain.tracks(k)=q; end
    s=tr.State; ego=out.actors(1);
    row=struct('id',tr.TrackID,'x',s(1),'y',s(3),'vx',s(2),'vy',s(4), ...
        'state',s,'covariance',tr.StateCovariance,'confirmed',true, ...
        'class','','sensorSources',{{}},'confidence',[],'uncertainty',[], ...
        'coasted',[],'rangeM',hypot(s(1)-out.x,s(3)-out.y), ...
        'relativeVxMps',s(2)-ego.vx,'relativeVyMps',s(4)-ego.vy, ...
        'attributeAvailability','UNAVAILABLE');
    if ~isempty(out.worldModel)
        idx=find([out.worldModel.id]==tr.TrackID,1);
        if ~isempty(idx)
            w=out.worldModel(idx);
            for f={'class','sensorSources','confidence','uncertainty','coasted'}
                row.(f{1})=w.(f{1});
            end
            row.attributeAvailability='AVAILABLE';
        end
    end
    if isempty(frame.tracks), frame.tracks=row; else, frame.tracks(k)=row; end
end
for k=1:numel(out.candidates)
    c=out.candidates(k); p=out.explainability.plannerResults(k);
    g=out.explainability.guardianResults(k); reasons={};
    if p.frontConflicts>0, reasons{end+1}='PLANNER_FRONT_ENVELOPE'; end
    if p.rearConflicts>0, reasons{end+1}='PLANNER_REAR_ENVELOPE'; end
    if p.sideConflicts>0, reasons{end+1}='PLANNER_SIDE_ENVELOPE'; end
    if p.boundaryViolation, reasons{end+1}='PLANNER_BOUNDARY'; end
    if ~p.comfortSafe, reasons{end+1}='PLANNER_COMFORT'; end
    if ~g.safe, reasons{end+1}='GUARDIAN_VETO'; end
    selected=~isempty(out.selected) && isequaln(c,out.selected);
    row=struct('id',c.id,'name',c.name, ...
        'targetSpeedKmh',c.targetSpeedKmh,'targetY',c.targetY, ...
        'trajectory',c.trajectory,'planner',p,'guardian',g, ...
        'safe',p.safe && g.safe,'selected',selected,'rejectionReasons',{reasons});
    if isempty(frame.candidates), frame.candidates=row; else, frame.candidates(k)=row; end
end
% Keep all existing output diagnostics, including sensor frames, actor truth,
% rear mitigation candidate scores and nextEgo. Truth is not a detection.
frame.source=plain;
end
