function catalog=autonex_demo_catalog()
% Presentation metadata only; no expected commands or algorithm parameters.
rows={ ...
'occluded_pedestrian','Occluded Pedestrian','A pedestrian emerges from behind a parked vehicle.','Occluded vulnerable road user','Occlusion evidence, track confirmation and uncertain-motion prediction'; ...
'unsignalized_intersection','Unsignalized Intersection','Cross traffic and a pedestrian share an uncontrolled junction.','Crossing conflict','Multi-object prediction, candidate rejection and Guardian checks'; ...
'cut_in','Highway Cut-In','A vehicle cuts toward ego while traffic approaches from behind.','Front and rear conflict','Cut-in intent, front/rear risk and minimum-risk selection'; ...
'animal_crossing','Animal Crossing','An animal crosses the vehicle path.','Crossing animal','Multimodal tracking and uncertainty-aware response'; ...
'dense_market','Dense Market','Several road users occupy a crowded, constrained street.','Multiple nearby road users','Fusion, safe-space search and candidate comparison'; ...
'missing_lane','Missing Lane / Unstructured Road','Road markings are unavailable and obstacles constrain free space.','Unstructured drivable space','Occupancy mapping, safe corridors and lane-independent planning'};
catalog=cell2struct(rows,{'id','title','challenge','risk','capability'},2);
end
